name: Build/release

on: push

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install
            - name: Build/release Electron app
              uses: cryogenicplanet/action-electron-builder@v2
              with:
                  # GitHub token, automatically provided to the action
                  # (No need to define this secret in the repo settings)
                  github_token: ${{ secrets.github_token }}
                  skip_install: true

                  # If the commit is tagged with a version (e.g. "v1.0.0"),
                  # release the app after building
                  release: ${{ startsWith(github.ref, 'refs/tags/v') }}
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref_name }}
                  body: |
                      Changes in this Release
                       - First Change
                  draft: false
                  prerelease: false
